-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkKdJUlNEx5AUN8yF
ry5yWb21HIEHzSYFucLmWXvjVuOgCgYIKoZIzj0DAQehRANCAASoTg7QxOzfOqaI
VMEKq8lOuUdN6sX2lFlV1uZBTXS0Ylq1QqhXomCdRNA53rcf/sjRQGZCbmBDIxaz
5vYGuJ4Y
-----END PRIVATE KEY-----